version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: phalkao/tarefas
    container_name: shouts-laravel-app
    ports:
      - "80:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-shouts
    depends_on:
      - mysql

  # Database
  mysql:
    image: 'mysql:5.7.22'
    container_name: shouts-laravel-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-shouts

# Networks
networks:
  laravel-shouts:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local